apiVersion: v1
kind: Service
metadata:
    name: mysql-svc
    namespace: teste
spec:
    selector:
        app: mysql-deploy
    ports:
        - name: "3306"
          port: 3306
          protocol: TCP
          targetPort: 3306
